import fs from "fs";
import path from "path";
import { promisify } from "util";
import { exec as execCallback } from "child_process";
import JSZip from "jszip";

const exec = promisify(execCallback);

interface AppInfo {
  name: string;
  packageName: string;
  version?: string;
  versionCode?: number;
}

/**
 * Creates a more realistic APK file structure
 * 
 * @param appInfo App information
 * @returns Buffer containing the APK data
 */
export async function createRealisticApkFile(appInfo: AppInfo): Promise<Buffer> {
  const zip = new JSZip();
  
  // Create META-INF directory
  const metaInf = zip.folder("META-INF");
  if (metaInf) {
    metaInf.file("MANIFEST.MF", "Manifest-Version: 1.0\r\nCreated-By: Android Gradle 7.3.1\r\n");
    metaInf.file("CERT.SF", "Signature-Version: 1.0\r\nCreated-By: 1.8.0_292 (Oracle Corporation)\r\nSHA-256-Digest: ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890\r\n");
    metaInf.file("CERT.RSA", Buffer.alloc(1024).fill(0x77)); // Dummy certificate file
  }
  
  // Create AndroidManifest.xml
  const androidManifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${appInfo.packageName}"
    android:versionCode="${appInfo.versionCode || 1}"
    android:versionName="${appInfo.version || '1.0'}">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="33" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="${appInfo.name}"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`;
  zip.file("AndroidManifest.xml", androidManifest);
  
  // Create classes.dex (dummy file with DEX magic number)
  const dexHeader = Buffer.from("6465780a30333500", "hex"); // DEX file magic number
  const dexFile = Buffer.alloc(1024 * 100); // 100KB dummy DEX file
  dexHeader.copy(dexFile);
  zip.file("classes.dex", dexFile);
  
  // Create resources.arsc (dummy resource file)
  const resourcesFile = Buffer.alloc(1024 * 200); // 200KB dummy resources file
  zip.file("resources.arsc", resourcesFile);
  
  // Create res folder with some resource files
  const res = zip.folder("res");
  const drawable = res?.folder("drawable");
  drawable?.file("background.xml", `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#FFFFFF" />
</shape>`);
  
  const layout = res?.folder("layout");
  layout?.file("activity_main.xml", `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <WebView
        android:id="@+id/webView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</LinearLayout>`);
  
  // Add icon files
  const mipmap = res?.folder("mipmap");
  const iconContent = Buffer.alloc(1024 * 5); // 5KB dummy icon
  mipmap?.file("ic_launcher.png", iconContent);
  
  // Add asset files
  const assets = zip.folder("assets");
  assets?.file("index.html", `<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${appInfo.name}</title>
    <style>
        body { font-family: sans-serif; margin: 0; padding: 20px; }
        h1 { color: #2196F3; }
    </style>
</head>
<body>
    <h1>${appInfo.name}</h1>
    <p>This is a WebView-based application generated by Webin2Apk.</p>
</body>
</html>`);
  
  // Create lib folder with dummy native libraries for different architectures
  const lib = zip.folder("lib");
  const arm64 = lib?.folder("arm64-v8a");
  arm64?.file("libapp.so", Buffer.alloc(1024 * 150)); // 150KB dummy native library
  
  const arm = lib?.folder("armeabi-v7a");
  arm?.file("libapp.so", Buffer.alloc(1024 * 120)); // 120KB dummy native library
  
  const x86 = lib?.folder("x86");
  x86?.file("libapp.so", Buffer.alloc(1024 * 130)); // 130KB dummy native library
  
  const x86_64 = lib?.folder("x86_64");
  x86_64?.file("libapp.so", Buffer.alloc(1024 * 145)); // 145KB dummy native library
  
  // Return the zipped content
  return await zip.generateAsync({ type: "nodebuffer" });
}

/**
 * Creates a more realistic AAB file structure
 * 
 * @param appInfo App information
 * @returns Buffer containing the AAB data
 */
export async function createRealisticAabFile(appInfo: AppInfo): Promise<Buffer> {
  const zip = new JSZip();
  
  // Create BundleConfig.pb (dummy protobuf file)
  zip.file("BundleConfig.pb", Buffer.alloc(1024));
  
  // Create base module
  const base = zip.folder("base");
  
  // Create AndroidManifest.xml for base module
  const androidManifest = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${appInfo.packageName}"
    split="base"
    android:versionCode="${appInfo.versionCode || 1}"
    android:versionName="${appInfo.version || '1.0'}">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="33" />
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="${appInfo.name}"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>`;
  base?.file("manifest/AndroidManifest.xml", androidManifest);
  
  // Create dex files
  const dexHeader = Buffer.from("6465780a30333500", "hex"); // DEX file magic number
  const dexFile = Buffer.alloc(1024 * 100); // 100KB dummy DEX file
  dexHeader.copy(dexFile);
  base?.file("dex/classes.dex", dexFile);
  
  // Create resource table
  base?.file("resources.pb", Buffer.alloc(1024 * 200)); // 200KB dummy resource file
  
  // Create res folder with resource files
  const res = base?.folder("res");
  if (res) {
    const drawable = res.folder("drawable");
    if (drawable) {
      drawable.file("background.xml", `<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#FFFFFF" />
</shape>`);
    }
    
    const layout = res.folder("layout");
    if (layout) {
      layout.file("activity_main.xml", `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <WebView
        android:id="@+id/webView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</LinearLayout>`);
    }
    
    // Add icon files
    const iconContent = Buffer.alloc(1024 * 5); // 5KB dummy icon
    const mipmap = res.folder("mipmap");
    if (mipmap) {
      mipmap.file("ic_launcher.png", iconContent);
    }
  }
  
  // Add asset files
  const assets = base?.folder("assets");
  assets?.file("index.html", `<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${appInfo.name}</title>
    <style>
        body { font-family: sans-serif; margin: 0; padding: 20px; }
        h1 { color: #2196F3; }
    </style>
</head>
<body>
    <h1>${appInfo.name}</h1>
    <p>This is a WebView-based application generated by Webin2Apk.</p>
</body>
</html>`);
  
  // Create BUNDLE-METADATA directory
  const metadata = zip.folder("BUNDLE-METADATA");
  metadata?.file("com.android.tools.build.gradle/app-metadata.properties", 
    `applicationId=${appInfo.packageName}\nversionCode=${appInfo.versionCode || 1}\nversionName=${appInfo.version || '1.0'}`);
  
  // Create native libraries for different architectures
  const arm64 = base?.folder("lib/arm64-v8a");
  arm64?.file("libapp.so", Buffer.alloc(1024 * 150)); // 150KB dummy native library
  
  const arm = base?.folder("lib/armeabi-v7a");
  arm?.file("libapp.so", Buffer.alloc(1024 * 120)); // 120KB dummy native library
  
  const x86 = base?.folder("lib/x86");
  x86?.file("libapp.so", Buffer.alloc(1024 * 130)); // 130KB dummy native library
  
  const x86_64 = base?.folder("lib/x86_64");
  x86_64?.file("libapp.so", Buffer.alloc(1024 * 145)); // 145KB dummy native library
  
  // Return the zipped content
  return await zip.generateAsync({ type: "nodebuffer" });
}

/**
 * Creates a more realistic IPA file structure
 * 
 * @param appInfo App information
 * @returns Buffer containing the IPA data
 */
export async function createRealisticIpaFile(appInfo: AppInfo): Promise<Buffer> {
  const zip = new JSZip();
  
  // Create Payload directory (required for IPA)
  const payload = zip.folder("Payload");
  
  // Create app bundle
  const appBundle = payload?.folder(`${appInfo.name}.app`);
  
  // Create Info.plist
  const infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>${appInfo.packageName.replace(/^com\./, 'io.')}</string>
    <key>CFBundleExecutable</key>
    <string>${appInfo.name}</string>
    <key>CFBundleVersion</key>
    <string>${appInfo.versionCode || 1}</string>
    <key>CFBundleShortVersionString</key>
    <string>${appInfo.version || '1.0'}</string>
    <key>CFBundleName</key>
    <string>${appInfo.name}</string>
    <key>CFBundleDisplayName</key>
    <string>${appInfo.name}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>armv7</string>
    </array>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
</dict>
</plist>`;
  appBundle?.file("Info.plist", infoPlist);
  
  // Create PkgInfo
  appBundle?.file("PkgInfo", "APPL????");
  
  // Create executable (a dummy binary file)
  appBundle?.file(appInfo.name, Buffer.alloc(1024 * 300)); // 300KB dummy binary
  
  // Create app icons
  if (appBundle) {
    const iconSet = appBundle.folder("AppIcon.appiconset");
    if (iconSet) {
      const iconSizes = [20, 29, 40, 58, 60, 76, 80, 87, 120, 152, 167, 180];
      for (const size of iconSizes) {
        iconSet.file(`Icon-${size}.png`, Buffer.alloc(1024 * 3)); // 3KB dummy icon
      }
      iconSet.file("Contents.json", JSON.stringify({ images: iconSizes.map(size => ({ 
        size: `${size}x${size}`, 
        idiom: "iphone",
        filename: `Icon-${size}.png`
      })) }));
    }
    
    // Create resource files
    const baseLproj = appBundle.folder("Base.lproj");
    if (baseLproj) {
      baseLproj.file("LaunchScreen.storyboardc", Buffer.alloc(1024 * 5)); // 5KB dummy storyboard
      baseLproj.file("Main.storyboardc", Buffer.alloc(1024 * 10)); // 10KB dummy storyboard
    }
  }
  
  // Create web resources
  const webResources = appBundle?.folder("www");
  webResources?.file("index.html", `<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${appInfo.name}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; margin: 0; padding: 20px; }
        h1 { color: #007AFF; }
    </style>
</head>
<body>
    <h1>${appInfo.name}</h1>
    <p>This is a WKWebView-based application generated by Webin2Apk.</p>
</body>
</html>`);
  
  // Create _CodeSignature folder (required for signed IPA)
  const codeSignature = appBundle?.folder("_CodeSignature");
  codeSignature?.file("CodeResources", Buffer.alloc(1024 * 2)); // 2KB dummy code signature plist
  
  // Create embedded frameworks
  const frameworks = appBundle?.folder("Frameworks");
  frameworks?.file("WebKit.framework", Buffer.alloc(1024 * 200)); // 200KB dummy framework

  // Return the zipped content
  return await zip.generateAsync({ type: "nodebuffer" });
}